### ISSUE TITLE
Not working in Torghast

### ISSUE THREAD

**Issue by Yaksimus** [KyrosKrane/AnnoyingPopupRemover#10]
When I buy powers in Torghast (solo, haven't tested with group) this addon doesn't prevent the dialogue box, though it's working fine for other alternative currency purchases.

**Comment by KyrosKrane** [comment]
Turns out this is a slightly different popup. This one is for non-refundable items. This will be an option in v13. The alpha is posted if you want to preview it; the final version should be out shortly.

**Comment by KyrosKrane** [comment]
Note to self: Fixed in commit f114519
