### ISSUE TITLE
TBC issue when looting with "Interact with mouseover" binding

### ISSUE THREAD

**Issue by KyrosKrane** [KyrosKrane/AnnoyingPopupRemover#11]
Reported on Curseforge by user MickeyPickey 2011-09-13

tbc not working if you loot with "Interact with mouseover" binding, can you fix it please ?

**Comment by cezeta** [comment]
I think this is the same error as #6 -> you use "Interact with mouseover" for botting and the addon removes the message but a bot cannot click on the item in the loot window so it will not loot it :-)

**Comment by KyrosKrane** [comment]
Sine TBC Classic no longer exists, I'm closing this issue. #6 still exists to track this issue in Classic.
