### ISSUE TITLE
Lua Error on Load in Wrath

### ISSUE THREAD

**Issue by Gogo1951** [KyrosKrane/AnnoyingPopupRemover#12]
1x ...faceAnnoyingPopupRemover\module_undercut.lua:109: attempt to index field 'AuctionHouseFrame' (a nil value)
[string "@AnnoyingPopupRemover\module_undercut.lua"]:109: in function `PreloadFunc'
[string "@AnnoyingPopupRemover\AnnoyingPopupRemover-v14.0.0-release.lua"]:377: in function `?'
[string "@AnnoyingPopupRemover\AnnoyingPopupRemover-v14.0.0-release.lua"]:410: in function <AnnoyingPopupRemover\AnnoyingPopupRemover.lua:409>

Locals:
(*temporary) = <table> {
 DELETE_GOOD_QUEST_ITEM = <table> {
 }
 CONFIRM_BINDER = <table> {
 }
 DELETE_GOOD_ITEM = <table> {
 }
}
(*temporary) = nil
(*temporary) = false
(*temporary) = "MISSING"
(*temporary) = "attempt to index field 'AuctionHouseFrame' (a nil value)"
APR = <table> {
 HIDE_STARTUP = false
 ToggleStartupMessage = <function> defined @AnnoyingPopupRemover\AnnoyingPopupRemover.lua:312
 PrintStatusSingle = <function> defined @AnnoyingPopupRemover\AnnoyingPopupRemover.lua:188
 DB = <table> {
 }
 OptionsTable = <table> {
 }
 NextOrdering = 240
 TogglePopup = <function> defined @AnnoyingPopupRemover\AnnoyingPopupRemover.lua:242
 Modules = <table> {
 }
 HandleAceSettingsChange = <function> defined @AnnoyingPopupRemover\AnnoyingPopupRemover.lua:145
 L = <table> {
 }
 IsClassic = false
 AceConfigCmd = <table> {
 }
 PRINT_STARTUP = true
 PRINT_CONFIRMATION = true
 ConfigFrame = <unnamed> {
 }
 HIDE_DIALOG = true
 AceConfigReg = <table> {
 }
 USER_ADDON_SHORT_NAME = "APR"
 SetDebug = <function> defined @AnnoyingPopupRemover\AnnoyingPopupRemover.lua:301
 Version = "v14.0.0-release"
 Utilities = <table> {
 }
 FORCE_HIDE_DIALOG = true
 PrintStatus = <function> defined @AnnoyingPopupRemover\AnnoyingPopupRemover.lua:202
 locale = "enUS"
 SHOW_DIALOG = false
 Events = <table> {
 }
 USER_ADDON_NAME = "Annoying Pop-up Remover"
 StoredDialogs = <table> {
 }
 Frame = <unnamed> {
 }
 NO_CONFIRMATION = false
 DebugMode = false
}
DebugPrint = <function> defined @AnnoyingPopupRemover\Libs\AddonUtilities\Utilities.lua:106
ThisModule = "undercut"
ControlAHUndercutPopup = <function> defined @AnnoyingPopupRemover\module_undercut.lua:57

**Comment by KyrosKrane** [comment]
I think I know what's causing this. I'll get this fixed today or tomorrow.

**Comment by KyrosKrane** [comment]
I just pushed v14.0.2-alpha; it should show up on here and on Curseforge in a few minutes. I think it will fix this issue. Please give it a try and let me know if the issue persists.

**Comment by Gogo1951** [comment]
Nice mate, thanks!

**Comment by Gogo1951** [comment]
Huh, not seeing a Wrath version show up yet on CurseForge.

Want a hand setting up CI/ CD so it auto-publishes?

Gogo#0298 on Discord. (=

![image](https://user-images.githubusercontent.com/55365231/188335093-7d2e7d63-7de3-43c5-b9ff-04b3c1ca737f.png)

**Comment by KyrosKrane** [comment]
Curseforge annoying hides alphas. :( You have to click on Files at the top of the page, then you'll see it in the list to download.

In any case, I'm testing it now, and will have it in full release as soon as I confirm it doesn't bug out.

**Comment by KyrosKrane** [comment]
Fixed in v14.1.0-release.
