### ISSUE TITLE
UI Error when trying to equip tradable item in combat

### ISSUE THREAD

**Issue by CraigeryTheKid** [KyrosKrane/AnnoyingPopupRemover#15]
Issue was 100% repeatable, not a big deal but still wanted to report.
When trying to equip tradable weapon, with the blue info text from party drops, while in combat, would get "action failed due to addon" error.
Issue occurred with this as the only addon. Issue did not occur when I unchecked "show warning for tradable item".

Thanks for the addon! It's a life saver when mass-buying BOE for transmog off AH.

**Comment by KyrosKrane** [comment]
Yeah, that's going to be an issue in any case. Blizz doesn't like addons messing with some things during combat. I'll probably add in a check to disable APR if you're in combat, at least for equipping gear.

**Comment by KyrosKrane** [comment]
This is fixed in v14.4.0
