### ISSUE TITLE
[wotlk classic] Cannot set hearthstone location.

### ISSUE THREAD

**Issue by Cheesehyvel** [KyrosKrane/AnnoyingPopupRemover#16]
In Wotlk Classic v14.2.2-release
Nothing happens when trying to set hearthstone location at an innkeeper.
It works when unchecking the checkbox in options or disabling the addon.

**Comment by KyrosKrane** [comment]
Fixed in version 14.3.0.

**Comment by KyrosKrane** [comment]
There might still be an issue with binding where you need to talk to the binder twice. I'm not sure why that's happening, but it doesn't happen all the time. Hopefully I'll get that fixed in a future release.
