### ISSUE TITLE
It used to hide that annoying pop up for the Heart of Azeroth when you had an unused Essence slot.  Why doesn't it do this anymore? Yes, I am using the retail version. I checked because Twitch tends to download the classic version even when you are on retail and update.

### ISSUE THREAD

**Issue by Reissa** [KyrosKrane/AnnoyingPopupRemover#3]

**Comment by KyrosKrane** [comment]
This is a surprise to me - APR never touched those popups that tell you about the necklace or an available azerite power. I played with the concept early in the expac, but it never worked out. I think you might have had a different addon that did that. The only pop-ups APR handles are the ones explicitly listed on the addon's page on Curse or WowInterface.

**Comment by KyrosKrane** [comment]
Closing for no response.  Please comment if this is still happening and you're sure it's APR, and I'll reopen and review.
