### ISSUE TITLE
Skip confirmation popup for using XP item on follower

### ISSUE THREAD

**Issue by teelolws** [KyrosKrane/AnnoyingPopupRemover#41]
This is the code I quickly whipped up that accomplishes it, though I'm sure you have a more secure method:

`hooksecurefunc("StaticPopup_Show", function(upgradeType) if upgradeType == "CONFIRM_FOLLOWER_UPGRADE" then StaticPopupDialogs["CONFIRM_FOLLOWER_UPGRADE"].OnAccept(StaticPopup1) StaticPopup_Hide("CONFIRM_FOLLOWER_UPGRADE") end end)`

**Comment by KyrosKrane** [comment]
Thanks for the idea! I'll research this and see how I can add it. I know that there's all kinds of weird UI errors in this area from personal experience (the UI will frequently from using follower upgrade items for some reason), so I'll want to make sure this doesn't make that worse.

**Comment by KyrosKrane** [comment]
Working on this in the Followers branch.

**Comment by KyrosKrane** [comment]
@Machou If you're able, could you please provide the French translation for these lines?

```lua
-- followers
L["followers_name"] = "Equip or upgrade followers with items"
L["followers_config"] = "Hide the confirmation pop-up when using items on followers at mission tables"
L["followers_hidden"] = "Confirmation pop-up when upgrading " .. APR.Utilities.CHAT_GREEN .. "followers" .. FONT_COLOR_CODE_CLOSE .. " at mission tables will be " .. APR.Utilities.CHAT_GREEN .. "hidden" .. FONT_COLOR_CODE_CLOSE .. "."
L["followers_shown"] = "Confirmation pop-up when upgrading " .. APR.Utilities.CHAT_RED .. "followers" .. FONT_COLOR_CODE_CLOSE .. " at mission tables will be " .. APR.Utilities.CHAT_RED .. "shown" .. FONT_COLOR_CODE_CLOSE .. "."
```

**Comment by Machou** [comment]
@KyrosKrane Follower is for BfA or Shadowlands ? who is ? :p

**Comment by KyrosKrane** [comment]
To be clear, so far I've tested the following:

WoD follower item level upgrades (armor/weapon)
WoD follower abilities and traits reroll
WoD follower abilities reroll
WoD follower traits reroll
WoD follower single-trait replacement

WoD shipyard equipment - fresh
WoD shipyard equipment - replacement

Legion class hall follower equipment - fresh
Legion class hall follower equipment - replacement

BFA mission table follower equipment - fresh
BFA mission table follower equipment - replacement

SL covenant table followers don't use equipment, so nothing to test.

**Comment by teelolws** [comment]
SL has the items that give the followers XP

**Comment by KyrosKrane** [comment]
Got them, thank you!

I'll go test in covenant tables later today, then put out a beta version.

**Comment by KyrosKrane** [comment]
> SL has the items that give the followers XP

Thanks for the reminder! Got that added in and tested now.

OK, everything should be set up in v20.0.0-beta, which should be packaging shortly. In the next day or two I'll do one last round of testing, update the documentation, and release it. Thanks all for the help and feedback!

**Comment by KyrosKrane** [comment]
v20 should be packaging momentarily. Thanks all!
