### ISSUE TITLE
Equipping refundable items on Cata Classic

### ISSUE THREAD

**Issue by Satanscakes** [KyrosKrane/AnnoyingPopupRemover#49]
There is no option in Cata Classic to be able to equip refundable items or buying pieces with dungeon/PvP currency faster using this add-on without the "are you sure you want to do this" message popping up

**Comment by KyrosKrane** [comment]
I have no way to test this on Cata, as I don't have any toons high enough to earn currency. Can you please try this build and let me know if those modules work, or if you see any strange issues or lua errors?

https://github.com/KyrosKrane/AnnoyingPopupRemover/releases/download/v21.0.0-beta/AnnoyingPopupRemover-v21.0.0-beta.zip

**Comment by KyrosKrane** [comment]
I was able to get a friend to test this, and it works. Releasing it as v21.0.0-release! :)
