### ISSUE TITLE
Hide popup for adding warband appearances

### ISSUE THREAD

**Issue by mergele4** [KyrosKrane/AnnoyingPopupRemover#56]
Is there any way to auto-accept this popup when attempting to "equip" an unequippable item with an unlearned appearance?

You cannot equip this item.
Its appearance will be added to your collection
and it will become Warbound until equipped.

**Comment by KyrosKrane** [comment]
Yes! This is planned for a future release. I'm currently not able to spend as much time on WoW as usual, so it may take a bit, but I definitely plan on adding this dialog.

**Comment by KyrosKrane** [comment]
Image for my reference
![image](https://github.com/user-attachments/assets/e68adabf-b809-4b77-96ad-339a43afacab)

**Comment by KyrosKrane** [comment]
Note to self, these may be two popups - one for warbound and one for BOE of wrong type.

**Comment by KyrosKrane** [comment]
This is solved by #58 and will be in v22.0.0-release.
