### ISSUE TITLE
Lua Error - Cata classic - version 21.5.0

### ISSUE THREAD

**Issue by telias82** [KyrosKrane/AnnoyingPopupRemover#57]
5x ...s/Blizzard_StaticPopup_Frame/Classic/StaticPopup.lua:1928: bad argument #1 to 'EquipPendingItem' (outside of expected range -2147483648 to 2147483647 - Usage: EquipPendingItem(index))
[string "=[C]"]: in function `EquipPendingItem'
[string "@Blizzard_StaticPopup_Frame/Classic/StaticPopup.lua"]:1928: in function `OnAccept'
[string "@AnnoyingPopupRemover/module_equip_refund.lua"]:126: in function `?'
[string "@AnnoyingPopupRemover/AnnoyingPopupRemover.lua"]:453: in function <AnnoyingPopupRemover/AnnoyingPopupRemover.lua:452>
[string "=[C]"]: in function `PickupInventoryItem'
[string "@ItemRack/ItemRack.lua"]:1443: in function `EquipItemByID'
[string "@ItemRack/ItemRack.lua"]:1407: in function <ItemRack/ItemRack.lua:1357>

Locals:
(*temporary) = <table> {
 slot = 0
}
(*temporary) = "outside of expected range -2147483648 to 2147483647 - Usage: EquipPendingItem(index)"

**Comment by KyrosKrane** [comment]
Was this on Classic, Cata Classic, or retail please? And what item were you
trying to equip?

**Comment by telias82** [comment]
Cata classic as the title states. PvP items (legacy weapons)On Jul 29, 2024, at 9:58 AM, KyrosKrane Sylvanblade ***@***.***> wrote:﻿
Was this on Classic, Cata Classic, or retail please? And what item were you
trying to equip?

**Comment by KyrosKrane** [comment]
This should be fixed with v21.6.0. Unfortunately I don't have access to Cata Classic right now to test. Please check it and let me know if there's any problem still. You can just reopen this issue, or reply to it and I'll reopen it.
