### ISSUE TITLE
annoying pop-up when using a transmog unlock

### ISSUE THREAD

**Issue by Vettic** [KyrosKrane/AnnoyingPopupRemover#60]
In retail, I'm spending Bullion to unlock some weapon transmogs, and this pop up shows for each item. 
![image](https://github.com/user-attachments/assets/9d66349a-0ff7-4529-a073-949b5f5aeb81)
There doesn't seem to be a checkbox for it in the addons options.

**Comment by KyrosKrane** [comment]
Can you please give me the name of one example item that gives this popup?

**Comment by KyrosKrane** [comment]
Oh, I just noticed you said bullion. Let me look into it, but since Remix is about to end, I don't know if I'll be able to update it in time.

**Comment by Vettic** [comment]
[Bullion](https://www.wowhead.com/item=213089/antique-bronze-bullion) is a Season 4 rewards from raid bosses, but this error pop up using the [transmog unlocks ](https://www.wowhead.com/item=217688/dream-raiders-shadowflame-poleax)

**Comment by zalidthebur** [comment]
Here are a couple:
[Crucible Raider's Bronzed Mutilator]
[Crucible Raider's Bronzed Wingblades]
[Vault Raider's Crystal Fists]
[Vault Raider's Crystal Scepter]
