### ISSUE TITLE
Doesn't work when I want to abandon a quest

### ISSUE THREAD

**Issue by Machou** [KyrosKrane/AnnoyingPopupRemover#61]
Hello!

Since TWW, AnnoyingPopupRemover doesn't work when I want to abandon a quest.

Can yopu check for this bug ?

Regards

**Comment by KyrosKrane** [comment]
It’s working normally for me. How are you trying to abandon the quests? As in, where exactly are you clicking, and what message is appearing?

Also, please check the settings for APR and make sure the option to abandon quests is checked there.

**Comment by Machou** [comment]
So I didn't touch anything in the configuration, and it used to work!

![A](https://github.com/user-attachments/assets/23974096-cff3-43ce-8b2a-95ea16f7bf17)
![WoWScrnShot_090124_001446](https://github.com/user-attachments/assets/543c0e73-7567-4900-b71e-801630f700cb)

![WoWScrnShot_090124_001446](https://github.com/user-attachments/assets/2a60de85-fbd2-4156-958b-d9938f486f9f)

**Comment by KyrosKrane** [comment]
I poked briefly through CQL's code. It uses its own dialogs, not the standard WoW ones. You'd have to talk to the CQL author to make an option not to show the dialog there.
