### ISSUE TITLE
Equip or use a Refundable item do not work on draenor plans

### ISSUE THREAD

**Issue by edu5ardo** [KyrosKrane/AnnoyingPopupRemover#63]
When I want to learn a building plan for Draenor Fortress, it is not possible, I must deactivate "Equip or use a Refundable item" for use it

**Comment by KyrosKrane** [comment]
I disabled the code that APR uses to bypass that dialog in commit bf6e4388f3758a545c44619cd3bc85df40501319; it will be in v23.4.0. When and if Blizz ever restores the ability for addons to use that protected function, I can re=enable this feature. I'll keep this open to remind me to check periodically, but sadly this is something I can't fix from my side.

**Comment by KyrosKrane** [comment]
Blizzard reverted their change, and I reverted mine. :) This is back to normal in v23.9.0-release.
